# Generated by Django 2.2.2 on 2019-06-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_enfermidade', models.CharField(max_length=100)),
                ('sintomas', models.TextField()),
                ('medicamentos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_equipamento', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_medicamento', models.CharField(max_length=100)),
                ('substancia', models.CharField(max_length=100)),
                ('validade', models.DateField()),
                ('contraindicacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sobrenome', models.CharField(max_length=60)),
                ('data_de_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('especialidade', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sobrenome', models.CharField(max_length=60)),
                ('data_de_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('sintomas', models.TextField()),
            ],
        ),
    ]
