# Generated by Django 2.2.2 on 2019-06-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermidade',
            old_name='nome_de_enfermidade',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='nome_de_equipamento',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='nome_de_medicamento',
            new_name='nome',
        ),
    ]
